server:
  port: 8888

management:
  context-path: /admin
  
logging:
  level:
    com.netflix.discovery: 'OFF'
    org.springframework.cloud: 'DEBUG'

spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/nguyentrung0306/spring-clould-config-example
          # The git repo will be cloned to this directory
          basedir: target/config11
          # within the cloned git repo search for properties in this directory
          searchPaths: dev-config
        native:
          searchLocations: file:../properties-git

# Activate this using -Dspring.profiles.active=native
#  profiles:
#    active: native
